services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    restart: unless-stopped

  consul:
    image: hashicorp/consul:1.20.3
    container_name: consul
    command: consul agent -dev -client=0.0.0.0 -ui
    ports:
      - "8500:8500"
    networks:
      - backend
    restart: unless-stopped

  auth-db:
    image: mysql:8
    container_name: auth-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - backend

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    volumes:
      - ./services/auth-service:/app
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_NAME: auth_db
      DB_USER: root
      DB_PASSWORD: password
      SERVICE_NAME: auth-service
      SERVICE_PORT: 8000
      CONSUL_HOST: consul
      JWT_SECRET_KEY: shared_secret_key
    entrypoint: /app/entrypoint.sh
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8000"

  product-db:
    image: mysql:8
    container_name: product-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    volumes:
      - product_db_data:/var/lib/mysql
    networks:
      - backend

  product-service:
    build: ./services/product-service
    container_name: product-service
    volumes:
      - ./services/product-service:/app
    depends_on:
      - product-db
    environment:
      DB_HOST: product-db
      DB_NAME: product_db
      DB_USER: root
      DB_PASSWORD: root
      SERVICE_NAME: product-service
      SERVICE_PORT: 8000
      CONSUL_HOST: consul
      JWT_SECRET_KEY: shared_secret_key
    entrypoint: /app/entrypoint.sh
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.product.rule=Host(`product.localhost`)"
      - "traefik.http.services.product.loadbalancer.server.port=8000"

  order-db:
    image: mysql:8
    container_name: order-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
    volumes:
      - order_db_data:/var/lib/mysql
    networks:
      - backend

  order-service:
    build: ./services/order-service
    container_name: order-service
    volumes:
      - ./services/order-service:/app
    depends_on:
      - order-db
    environment:
      DB_HOST: order-db
      DB_NAME: order_db
      DB_USER: root
      DB_PASSWORD: root
      SERVICE_NAME: order-service
      SERVICE_PORT: 8000
      CONSUL_HOST: consul
      JWT_SECRET_KEY: shared_secret_key
    entrypoint: /app/entrypoint.sh
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.rule=Host(`order.localhost`)"
      - "traefik.http.services.order.loadbalancer.server.port=8000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    restart: always

  notification-db:
    image: mysql:8
    container_name: notification-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_db
    volumes:
      - notification_db_data:/var/lib/mysql
    networks:
      - backend

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    volumes:
      - ./services/notification-service:/app
    depends_on:
      - notification-db
      - rabbitmq
    environment:
      DB_HOST: notification-db
      DB_NAME: notification_db
      DB_USER: root
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: admin
      RABBITMQ_PASS: admin123
      SERVICE_NAME: notification-service
      SERVICE_PORT: 8000
      CONSUL_HOST: consul
      JWT_SECRET_KEY: shared_secret_key
    entrypoint: /app/entrypoint.sh
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notification.rule=Host(`notification.localhost`)"
      - "traefik.http.services.notification.loadbalancer.server.port=8000"

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"

networks:
  backend:
    driver: bridge

volumes:
  auth_db_data:
  order_db_data:
  product_db_data:
  notification_db_data: